In [1]:
import pandas as pd
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import cross_validation
from xgboost import XGBClassifier

import matplotlib.pyplot as plt
%matplotlib inline

/home/kabin/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/home/kabin/anaconda3/lib/python3.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
data = pd.read_csv('final_dataset1.csv')

data = data[data.MW > 3]

data.drop(['Unnamed: 0', 'HomeTeam', 'AwayTeam', 'HM1', 'HM2', 'HM3', 'AM1', 'AM2', 'AM3', 'Date', 'MW', 'HTFormPtsStr', 'ATFormPtsStr', 'FTHG', 'FTAG',
           'HTGS', 'ATGS', 'HTGC', 'ATGC','DiffLP','DiffPts','DiffFormPts',
           'HM4','HM5','AM4','AM5','HTLossStreak5','ATLossStreak5','HTWinStreak5','ATWinStreak5',
           'HTWinStreak3','HTLossStreak3','ATWinStreak3','ATLossStreak3'],1, inplace=True)

display(data.head())

   FTR   HTP   ATP  HomeTeamLP  AwayTeamLP  HTFormPts  ATFormPts  HTGD  ATGD
30   W  1.25  1.00         1.0        17.0          5          4  0.50  0.25
31   D  0.75  0.25         7.0         9.0          3          1 -0.50 -0.75
32   W  1.00  1.00        10.0        13.0          4          4  0.00  0.25
33   D  0.75  0.50        18.0        15.0          3          2 -0.25 -0.25
34   D  1.00  1.50         5.0         2.0          4          6  0.00  0.75

In [3]:
data.shape[1]

9

In [4]:
n_matches = data.shape[0]

n_features = data.shape[1] - 1


n_homewins = len(data[data.FTR == 'W'])

win_rate = (float(n_homewins) / (n_matches)) * 100

# Print the results
print ("Total number of matches: {}".format(n_matches))
print ("Number of features: {}".format(n_features))
print ("Number of matches won by home team: {}".format(n_homewins))
print ("Win rate of home team: {:.2f}%".format(win_rate))

Total number of matches: 5600
Number of features: 8
Number of matches won by home team: 2603
Win rate of home team: 46.48%

In [5]:
X_all = data.drop(['FTR'],1)
y_all = data['FTR']


from sklearn.preprocessing import scale

cols = [['HTGD','ATGD','HTP','ATP','HomeTeamLP','AwayTeamLP']]
for col in cols:
    X_all[col] = scale(X_all[col])
X_all

,HTP,ATP,HomeTeamLP,AwayTeamLP,HTFormPts,ATFormPts,HTGD,ATGD
30,-0.043829,-0.611968,-1.685031,1.196371,5,4,0.753719,0.355995
31,-1.120644,-2.238746,-0.604491,-0.243684,3,1,-0.737082,-1.138834
32,-0.582236,-0.611968,-0.064221,0.476343,4,4,0.008318,0.355995
33,-1.120644,-1.696487,1.376498,0.836357,3,2,-0.364382,-0.391419
34,-0.582236,0.472551,-0.964671,-1.503733,4,6,0.008318,1.103409
35,0.494579,0.472551,0.656139,0.116329,6,6,0.008318,0.355995
36,-1.659052,-0.611968,1.016318,0.296336,2,4,-0.364382,0.355995
37,-0.043829,-0.611968,-0.424401,1.376378,5,4,0.381019,-0.391419
38,-0.582236,-1.696487,-1.144761,-0.783705,4,2,-0.364382,-0.765127
39,-0.582236,0.472551,1.196408,-1.503733,4,6,0.381019,1.103409
40,-0.151510,0.255647,0.656139,-1.323726,6,7,-0.588002,0.580219
41,-1.012962,-0.611968,1.376498,-0.783705,4,5,-0.588002,-0.316678
42,0.709942,-1.479583,-0.424401,0.836357,8,3,0.604639,-0.316678
43,0.279216,-0.178160,-1.144761,1.376378,7,6,0.306479,-0.615644
44,0.709942,-1.045776,-1.685031,-0.603698,8,4,2.393600,-0.615644
45,-0.582236,-1.045776,0.295959,0.476343,5,4,0.306479,-0.017712
46,1.140668,-0.611968,0.115869,-0.963712,9,5,0.902799,-0.017712
47,-1.443689,-1.045776,1.016318,1.376378,3,4,-0.289842,-0.316678
48,0.279216,-1.913391,-0.064221,-0.243684,7,2,0.306479,-0.914609
49,0.279216,-0.178160,-1.504941,0.656350,7,6,0.902799,-0.615644
50,0.135641,-0.973474,-0.784581,1.196371,8,5,0.256785,-1.263403
51,-0.941175,0.834057,1.376498,-0.063677,5,10,-0.240148,0.480564
52,-0.223298,1.195564,0.476049,-1.683740,7,11,0.256785,2.722807
53,-0.223298,-1.334981,-1.324851,1.376378,7,4,0.256785,-0.765127
54,-1.659052,0.834057,0.836228,0.116329,3,10,-0.488615,0.729702
55,-1.300113,-1.334981,-0.604491,1.016364,4,4,-1.234016,-0.266850
56,-0.582236,1.195564,-0.964671,-0.423691,6,11,0.008318,0.729702
57,-0.582236,-0.973474,1.376498,0.296336,6,5,-0.737082,-0.017712
58,-2.017990,0.834057,-0.244311,-1.143719,2,10,-0.985549,0.480564
59,-0.941175,-1.696487,1.196408,0.836357,5,3,-1.234016,-0.515989
...,...,...,...,...,...,...,...,...
6050,-0.103652,-1.816989,1.376498,1.196371,7,0,-0.240148,-1.844725
6051,-0.283121,0.773806,0.476049,0.296336,2,9,-0.447204,0.688179
6052,0.853518,1.798074,-1.144761,0.656350,10,13,0.505252,1.227978
6053,0.494579,1.075062,-0.604491,-1.503733,10,13,0.505252,1.311024
6054,-0.342944,0.532802,-0.424401,-0.783705,7,10,-0.612849,0.439041
6055,0.135641,1.376317,-1.685031,-0.963712,7,11,0.298196,1.601685
6056,-1.778698,-0.973474,1.196408,0.836357,0,5,-1.813772,-1.097311
6057,-0.283121,-0.310713,1.376498,0.476343,3,2,-0.778493,-0.474466
6058,-0.402767,0.050794,-0.064221,-0.243684,6,4,-0.364382,-0.599035
6059,1.810687,-0.129960,0.656139,0.116329,13,6,1.250652,0.231426
6060,-0.931474,0.912221,1.376498,-1.143719,3,10,-1.079563,0.507498
6061,-0.698649,0.032881,1.016318,-1.683740,8,4,-0.676644,0.224692
6062,0.698301,-0.260232,0.295959,-0.423691,8,7,0.572405,-0.542922
6063,0.640095,-0.201609,-0.784581,1.376378,10,7,0.532113,-0.340919
6064,0.989332,1.146711,-1.504941,-1.323726,10,9,1.217076,0.992307
6065,1.338570,0.560485,-0.964671,-0.603698,9,10,1.579703,0.547898
6066,0.698301,0.912221,0.295959,-1.143719,8,10,0.572405,0.507498
6067,0.640095,0.032881,-0.784581,-1.683740,10,4,0.532113,0.224692
6068,-0.931474,-0.201609,1.376498,1.376378,3,7,-1.079563,-0.340919
6069,-0.698649,-0.201609,1.016318,0.116329,8,5,-0.676644,0.143891
6070,1.117999,-1.810647,-1.324851,1.196371,9,1,0.989108,-1.787904
6071,0.041183,1.785390,-1.685031,0.656350,5,11,0.243708,1.241091
6072,-0.242189,-0.840288,0.115869,1.376378,4,3,0.047550,-1.001152
6073,-0.808934,1.214590,0.836228,-0.963712,9,8,-0.972472,1.477116
6074,0.664603,-0.383648,-0.604491,-0.063677,13,5,0.596792,-0.371751
6075,-0.015491,0.757951,-0.244311,0.296336,1,10,-0.580156,0.572352
6076,-0.128840,0.929191,-0.424401,-1.503733,9,8,-0.383998,1.162416
6077,-0.242189,-0.611968,1.376498,1.016364,6,11,-0.383998,-0.568439
6078,-0.355538,0.586711,0.476049,-0.783705,2,8,-0.540924,0.493676
6079,0.834626,-0.383648,-1.144761,1.376378,10,4,0.479098,-0.804464

In [6]:
from sklearn.cross_validation import train_test_split

# Shuffle and split the dataset into training and testing set.
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, 
                                                    test_size = .2,
                                                    random_state = 12)

In [7]:
X_train.shape[1]

8

In [8]:
modelLR = XGBClassifier()
modelLR.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [9]:
modelRandom = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 42)
modelRandom.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [10]:
randomPredictions = modelRandom.predict(X_test)
display(randomPredictions)

array(['W', 'D', 'L', ..., 'W', 'W', 'D'], dtype=object)

In [11]:
predictionsLR = modelLR.predict(X_test)
display(predictionsLR)

/home/kabin/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

array(['W', 'W', 'W', ..., 'W', 'W', 'W'], dtype=object)

In [12]:
from sklearn.metrics import accuracy_score
print('Accuracy score:', accuracy_score(y_test,randomPredictions))
print('Accuracy score:', accuracy_score(y_test,predictionsLR))

Accuracy score: 0.475
Accuracy score: 0.5205357142857143

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictionsLR))

             precision    recall  f1-score   support

          D       0.23      0.03      0.06       279
          L       0.53      0.41      0.46       332
          W       0.53      0.86      0.66       509

avg / total       0.46      0.52      0.45      1120

In [ ]:
drone= pd.read_csv('final_dataset1.csv')
ht="Man United"
at="Man City"

In [ ]:
a = drone["HomeTeam"]
count = 0
for i in a:
    if i == ht:
        count= count+1

b= drone["AwayTeam"]
count2 = 0
for i in b:
    if i == at:
        count2= count2+1

count,count2

In [ ]:
a= (drone[drone["HomeTeam"] == ht].sum().HTP)/count
b= (drone[drone["AwayTeam"] == at].sum().ATP)/count2
c= (drone[drone["HomeTeam"] == ht].sum().HomeTeamLP)/count
d= (drone[drone["AwayTeam"] == at].sum().AwayTeamLP)/count2
e= (drone[drone["HomeTeam"] == ht].sum().HTFormPts)/count
f= (drone[drone["AwayTeam"] == at].sum().ATFormPts)/count2
g= (drone[drone["HomeTeam"] == ht].sum().HTGD)/count
h= (drone[drone["AwayTeam"] == at].sum().ATGD)/count2

In [ ]:
p=[a,b,c,d,e,f,g,h]
print(p)
len(p)

In [ ]:
df = pd.DataFrame({'HTP': p[0],'ATP': p[1],'HomeTeamLP': p[2],'AwayTeamLP': p[3],'HTFormPts': p[4],'ATFormPts': p[5],
                   'HTGD': p[6],'ATGD': p[7]}, index=[0])
df

In [ ]:
result= modelLR.predict(df)

In [ ]:
print(result)

In [ ]:
import pickle
filename = 'xgbPredictionModel.sav'
pickle.dump(modelLR, open(filename, 'wb'))

In [ ]:
try:
    predictionModel = pickle.load(open('xgbPredictionModel.sav','rb'))
except:
    print("File is not loaded")

In [ ]:
help= predictionModel.predict(df)
help